export enum Role {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum DayPlanStatus {
  SCHEDULED = 'SCHEDULED',
  VOTING_OPEN = 'VOTING_OPEN',
  RUNOFF_VOTING = 'RUNOFF_VOTING',
  TIE_ADMIN_DECISION = 'TIE_ADMIN_DECISION',
  ORDERING_OPEN = 'ORDERING_OPEN',
  ORDERING_CLOSED = 'ORDERING_CLOSED',
  ORDERED = 'ORDERED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum TieBreakStrategy {
  RUNOFF = 'RUNOFF',
  ADMIN_DECISION = 'ADMIN_DECISION',
}

export enum NotificationType {
  VOTING_OPENED = 'VOTING_OPENED',
  VOTING_REMINDER = 'VOTING_REMINDER',
  RUNOFF_STARTED = 'RUNOFF_STARTED',
  WINNER_ANNOUNCED = 'WINNER_ANNOUNCED',
  ORDERING_REMINDER = 'ORDERING_REMINDER',
  TIE_ADMIN_ACTION = 'TIE_ADMIN_ACTION',
  ORGANIZER_REMINDER = 'ORGANIZER_REMINDER',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  DAY_CANCELLED = 'DAY_CANCELLED',
  GENERIC = 'GENERIC',
}
